using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using Fayora.Application.Features.ChatbotModule.Commands.SendChatbotMessage;
using Fayora.Infrastructure.Settings;
using Microsoft.Extensions.Options;

namespace Fayora.Infrastructure.Services.Chatbot;

public class OpenRouterChatbotService
{
    private readonly HttpClient _httpClient;
    private readonly OpenRouterSettings _settings;
    private readonly string _model;

    public OpenRouterChatbotService(HttpClient httpClient, IOptions<OpenRouterSettings> settings)
    {
        _httpClient = httpClient;
        _settings = settings.Value;
        _model = _settings.GeminiModel ?? "google/gemini-2.5-flash";
    }

    public async Task<AgentDecision> ThinkAsync(
        string userPrompt,
        List<(string Role, string Content)> history,
        CancellationToken cancellationToken = default)
    {
        var systemPrompt = ChatbotPrompts.ThinkSystemPrompt;
        
        var messages = new List<object>
        {
            new { role = "system", content = systemPrompt }
        };

        foreach (var msg in history)
        {
            messages.Add(new
            {
                role = msg.Role.ToLower() switch
                {
                    "user" or "tourist" => "user",
                    _ => "assistant"
                },
                content = msg.Content
            });
        }

        messages.Add(new { role = "user", content = userPrompt });

        var requestBody = new
        {
            model = _model,
            messages = messages,
            response_format = new { type = "json_object" },
            max_tokens = 400,
            temperature = 0.1
        };

        var rawResponse = await CallOpenRouterAsync(requestBody, cancellationToken);
        if (string.IsNullOrWhiteSpace(rawResponse))
        {
            return new AgentDecision("reply", null, new(), new(), new SearchFilters(2, null, null), "Fallback thinking");
        }

        try
        {
            var cleanedJson = CleanThinkJson(rawResponse);
            var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
            var decision = JsonSerializer.Deserialize<AgentDecision>(cleanedJson, options);
            if (decision != null && !string.IsNullOrEmpty(decision.Action))
            {
                return decision;
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[OpenRouter Think Parse Exception] {ex.Message}");
        }

        return new AgentDecision("reply", null, new(), new(), new SearchFilters(2, null, null), "Parse error fallback");
    }

    public async Task<(string Text, List<string> Suggestions)> RespondAsync(
        string userPrompt,
        List<(string Role, string Content)> history,
        string systemPrompt,
        CancellationToken cancellationToken = default)
    {
        var messages = new List<object>
        {
            new { role = "system", content = systemPrompt }
        };

        foreach (var msg in history)
        {
            messages.Add(new
            {
                role = msg.Role.ToLower() switch
                {
                    "user" or "tourist" => "user",
                    _ => "assistant"
                },
                content = msg.Content
            });
        }

        messages.Add(new { role = "user", content = userPrompt });

        var requestBody = new
        {
            model = _model,
            messages = messages,
            max_tokens = 800,
            temperature = 0.65
        };

        var rawResponse = await CallOpenRouterAsync(requestBody, cancellationToken);
        if (string.IsNullOrWhiteSpace(rawResponse))
        {
            return ("عذراً، حدثت مشكلة مؤقتة في الحصول على رد. يرجى المحاولة لاحقاً.", new List<string> { "عايز فندق 🏨", "خطة رحلة 📅", "أماكن سياحية 🏛️" });
        }

        // Clean any reasoning tags if they are generated by the model (e.g. DeepSeek-like reasoning tags)
        var cleanedText = CleanReasoningTags(rawResponse);

        // Extract SUGGESTIONS
        var match = Regex.Match(cleanedText, @"SUGGESTIONS:\s*(\[.*?\])", RegexOptions.Singleline | RegexOptions.IgnoreCase);
        var suggestions = new List<string>();
        var text = cleanedText;

        if (match.Success)
        {
            try
            {
                suggestions = JsonSerializer.Deserialize<List<string>>(match.Groups[1].Value, new JsonSerializerOptions { PropertyNameCaseInsensitive = true }) ?? new();
                text = cleanedText.Substring(0, match.Index).Trim();
            }
            catch
            {
                suggestions = new();
            }
        }

        if (suggestions.Count == 0)
        {
            suggestions = new List<string> { "عايز فندق 🏨", "خطة رحلة 📅", "أماكن سياحية 🏛️", "مرشد سياحي 🗺️" };
        }

        return (text, suggestions);
    }

    private async Task<string?> CallOpenRouterAsync(object requestBody, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(_settings.ApiKey))
        {
            Console.WriteLine("[OpenRouter API Error] ApiKey is empty.");
            return null;
        }

        var url = "https://openrouter.ai/api/v1/chat/completions";
        int maxRetries = 3;
        int delayMs = 2000;

        for (int retry = 0; retry <= maxRetries; retry++)
        {
            try
            {
                using var request = new HttpRequestMessage(HttpMethod.Post, url);
                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _settings.ApiKey);
                request.Headers.Add("HTTP-Referer", "https://fayora.com");
                request.Headers.Add("X-Title", "Fayora Travel");
                request.Content = JsonContent.Create(requestBody);

                var response = await _httpClient.SendAsync(request, cancellationToken);

                if (response.StatusCode == System.Net.HttpStatusCode.TooManyRequests && retry < maxRetries)
                {
                    Console.WriteLine($"[OpenRouter] Rate limited (429). Retrying in {delayMs}ms...");
                    await Task.Delay(delayMs, cancellationToken);
                    delayMs *= 2;
                    continue;
                }

                if (!response.IsSuccessStatusCode)
                {
                    var err = await response.Content.ReadAsStringAsync(cancellationToken);
                    Console.WriteLine($"[OpenRouter] Error: {response.StatusCode}, Body: {err}");
                    return null;
                }

                var responseContent = await response.Content.ReadAsStringAsync(cancellationToken);
                using var jsonDoc = JsonDocument.Parse(responseContent);
                var root = jsonDoc.RootElement;
                var choice = root.GetProperty("choices")[0];
                var msgObj = choice.GetProperty("message");
                return msgObj.GetProperty("content").GetString();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[OpenRouter Call Exception] {ex.Message}");
                if (retry == maxRetries) return null;
                await Task.Delay(delayMs, cancellationToken);
            }
        }

        return null;
    }

    private static string CleanThinkJson(string text)
    {
        // Remove reasoning tag (think) if it exists
        text = CleanReasoningTags(text);

        // Remove markdown block tags if they exist
        text = Regex.Replace(text, @"^```json\s*", "", RegexOptions.IgnoreCase | RegexOptions.Multiline);
        text = Regex.Replace(text, @"\s*```$", "", RegexOptions.IgnoreCase | RegexOptions.Multiline);
        return text.Trim();
    }

    private static string CleanReasoningTags(string text)
    {
        if (string.IsNullOrEmpty(text)) return text;
        
        // Remove </think> and anything before it
        if (text.Contains("</think>"))
        {
            text = text.Split("</think>", 2)[1];
            if (text.StartsWith(">")) text = text.Substring(1);
        }
        
        text = Regex.Replace(text, @"<think\b[^>]*>.*?</think\s*>", "", RegexOptions.Singleline | RegexOptions.IgnoreCase);
        text = Regex.Replace(text, @"<think\b[^>]*>.*", "", RegexOptions.Singleline | RegexOptions.IgnoreCase);
        return text.Trim();
    }
}
