namespace Fayora.Contracts.AdminModule.UpdateAccommodation;

public record GetDetailedAccommodationResponse(
    Guid Id,
    Guid OwnerId,
    string OwnerName,
    string OwnerEmail,
    string OwnerPhone,
    string Title,
    string? Description,
    string Type,
    int LocationId,
    string LocationName,
    string AddressDetails,
    decimal Latitude,
    decimal Longitude,
    int NumberOfRooms,
    int BedRooms,
    int BathRooms,
    int NumberOfBeds,
    int MaxGuests,
    TimeSpan CheckInTime,
    TimeSpan CheckOutTime,
    decimal PricePerNight,
    decimal CommissionRate,
    string Status,
    decimal Rating,
    int ReviewCount,
    int Views,
    string MainImageUrl,
    List<string> ImageUrls,
    List<string> Amenities,
    DateTimeOffset CreatedAt,
    string? AdminNotes,
    string? VerificationDocumentUrl
);
